const FETCH_BALANCE = 'FETCH_BALANCE';
const INITIALIZE_BALANCE = 'INITIAlIZE_BALANCE';
const CONNECTION_ERROR = 'CONNECTION_ERROR';
const INITIALIZE_TRANSACTION = 'INITIAlIZE_TRANSACTION';
const SUCCESSFUL_TRANSACTION = 'SUCCESSFUL_TRANSACTION';
const CLEAR_TRANSACTION = 'CLEAR_TRANSACTION';
const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';

export {
  INITIALIZE_BALANCE,
  FETCH_BALANCE,
  CONNECTION_ERROR,
  INITIALIZE_TRANSACTION,
  SUCCESSFUL_TRANSACTION,
  CLEAR_TRANSACTION,
  FETCH_TRANSACTIONS
};
