const FETCH_BALANCE = 'FETCH_BALANCE';
const CONNECTION_ERROR = 'CONNECTION_ERROR';
const SEND_TRANSACTION = 'SEND_TRANSACTION';
const SUCCESSFUL_TRANSACTION = 'SUCCESSFUL_TRANSACTION';
const CLEAR_TRANSACTION = 'CLEAR_TRANSACTION';
const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';

export {
  FETCH_BALANCE,
  CONNECTION_ERROR,
  SEND_TRANSACTION,
  SUCCESSFUL_TRANSACTION,
  CLEAR_TRANSACTION,
  FETCH_TRANSACTIONS
};
