const DIFFICULTY = 1;
const MINE_RATE_MIN = 1 || 15000;
const MINE_RATE_MAX = 45000;
const INITIAL_BALANCE = 500;
const MINING_REWARD = 20;

module.exports = {
  DIFFICULTY,
  MINE_RATE_MIN,
  MINE_RATE_MAX,
  INITIAL_BALANCE,
  MINING_REWARD
};
